### ISSUE TITLE
Is it possible to get the output of the ChatGPT and T5 models for AggreFact

### ISSUE THREAD

**Issue by guihuzhang** [Babelscape/FENICE#1]
Thank you for sharing the code of your paper. 

I want to reproduce some results and also compute the confidence intervals on different subsets. Is it possible to get the output score of your ChatGPT and T5 on each sample of AggreFact?

**Comment by KarimAsh11** [comment]
Hi @guihuzhang! 
Thanks for your interest in our work.

You can now find the files [here](https://github.com/Babelscape/FENICE/tree/master/outputs).
I guess the fields you might be interested in are "text_claims" and "score".

Feel free to reach out if you have any questions or need further clarification.

**Comment by guihuzhang** [comment]
Thank you very much.
