### ISSUE TITLE
It seems around 5 percent of data missed claim extractions and scores

### ISSUE THREAD

**Issue by guihuzhang** [Babelscape/FENICE#2]
The aggrefact dataset has over 10k text summaries, but the claim and score file has only 9.3k summaries. If I want to evaluate the outputs, should I give a default score to the missed summaries?

**Comment by KarimAsh11** [comment]
Hi, I think you're referring to the fact that in aggrefact, the authors ignore "LEAD3" and "Gold" from the old category as mentioned [here](https://github.com/Liyan06/AggreFact/blob/f0654b245232cd724d5caa5db4950abfb12d795e/utils.py).
When you ignore those you end up with 9466 samples (all found in our files).

**Comment by guihuzhang** [comment]
Thank you.
